IRIS_ARDUINO_CLI=arduino-cli
IRIS_ARDUINO_CONFIG="$IRIS_ROOT/.arduino-cli/arduino-cli.yaml"
IRIS_NM=xtensa-esp-elf-nm
IRIS_FQBN='esp32:esp32:esp32s3:FlashSize=16M,PartitionScheme=huge_app,PSRAM=enabled,FlashMode=qio,CDCOnBoot=default,USBMode=hwcdc,UploadSpeed=921600'
IRIS_BUILD_JOBS=4
IRIS_BUILD_EXTRA_FLAGS='-DNOOB_ENABLE_EXTERNAL_I2C=1 -DNOOB_ENABLE_SH1107=0 -DNOOB_ENABLE_SOFT_I2C_DIAGNOSTICS=0'
