IRIS_ARDUINO_CLI=arduino-cli
IRIS_ARDUINO_CONFIG="$IRIS_ROOT/.arduino-cli/arduino-cli.yaml"
IRIS_NM=xtensa-esp-elf-nm
IRIS_COMMON_LIBRARY="$IRIS_ROOT/../esp/common"
IRIS_SKETCH="$IRIS_ROOT/firmware/iris_noob"
IRIS_FQBN='esp32:esp32:esp32s3:FlashSize=16M,PartitionScheme=huge_app,PSRAM=enabled,FlashMode=qio,CDCOnBoot=default,USBMode=hwcdc,UploadSpeed=921600'
IRIS_BUILD_JOBS=4
IRIS_BUILD_EXTRA_FLAGS=''
