#include "contact_book.h"
#include "conversation_activity.h"
#include "protocol.h"
#include "service_config.h"
#include <stdio.h>
#include <string.h>
static const contact*next_arbiter(const contact_book*b,int after){const contact*best=NULL;size_t i;for(i=0;i<b->count;i++){const contact*c=&b->items[i];if(c->arbiter_priority<=after)continue;if(!best||c->arbiter_priority<best->arbiter_priority)best=c;}return best;}
static int print_file(const char*p){FILE*f=fopen(p,"r");char line[8192];if(!f)return 1;while(fgets(line,sizeof(line),f))fputs(line,stdout);fclose(f);return 0;}
int main(int argc,char**argv){service_config config;contact_book book;const contact*arbiter,*self;contact authenticated;const char*config_path=NULL,*operation=NULL,*message="";char error[256]="missing arguments",reply[256],command[COUNCIL_MESSAGE_LENGTH];int i,priority=0;for(i=1;i<argc;i++){if(!strcmp(argv[i],"--config")&&++i<argc)config_path=argv[i];else if(!operation){operation=argv[i];if(i+1<argc)message=argv[++i];}else return 2;}if(!config_path||!operation||service_config_load(config_path,&config,error,sizeof(error))||contact_book_load(config.contacts_path,&book,error,sizeof(error))||!(self=contact_book_find(&book,config.name))){fprintf(stderr,"configuration: %s\n",error);return 2;}if(!strcmp(operation,"summary"))return print_file(config.summary_path);if(!strcmp(operation,"inbox"))return print_file(config.inbox_path);while((arbiter=next_arbiter(&book,priority))!=NULL){priority=arbiter->arbiter_priority;authenticated=*arbiter;snprintf(authenticated.shared_key,sizeof(authenticated.shared_key),"%s",self->shared_key);if(protocol_send_command(&authenticated,config.name,"BUSY",reply,sizeof(reply)))continue;if(!strcmp(operation,"busy")){printf("%s %s\n",arbiter->name,reply);return 0;}if(strncmp(reply,"IDLE",4)){printf("%s %s\n",arbiter->name,reply);return 3;}if(strcmp(operation,"initiate")||strchr(message,'\n')||strchr(message,'\r'))return 2;snprintf(command,sizeof(command),"INITIATE %s",message);if(!protocol_send_command(&authenticated,config.name,command,reply,sizeof(reply))){if(!strcmp(reply,"ACCEPTED"))conversation_activity_mark(config.activity_path);printf("%s via %s\n",reply,arbiter->name);return strcmp(reply,"ACCEPTED")?1:0;}}fputs("no arbiter reachable\n",stderr);return 1;}
