#include "file_transfer.h"
#include "authentication.h"
#include "protocol.h"
#include "sha256.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
static void digest_hex(const uint8_t *bytes, char output[65]) { static const char digits[]="0123456789abcdef"; size_t i; for(i=0;i<32;i++){output[i*2]=digits[bytes[i]>>4];output[i*2+1]=digits[bytes[i]&15];} output[64]=0; }
int file_transfer_name_is_safe(const char *name) { size_t i,n=strlen(name); if(!n||n>=COUNCIL_FILE_NAME||!strcmp(name,".")||!strcmp(name,".."))return 0; for(i=0;i<n;i++)if(!isalnum((unsigned char)name[i])&&name[i]!='.'&&name[i]!='_'&&name[i]!='-')return 0; return 1; }
static const char *base_name(const char *path) { const char *slash=strrchr(path,'/'),*backslash=strrchr(path,'\\'),*base=slash?slash+1:path; if(backslash&&backslash+1>base)base=backslash+1; return base; }
int file_transfer_describe(const char *path,char name[COUNCIL_FILE_NAME],uint64_t *size,char digest[65]) { FILE *file; uint8_t buffer[16384],bytes[32]; size_t count; sha256_ctx hash; const char *base=base_name(path); if(!file_transfer_name_is_safe(base))return-1; file=fopen(path,"rb"); if(!file)return-1; sha256_init(&hash); *size=0; while((count=fread(buffer,1,sizeof(buffer),file))>0){sha256_update(&hash,buffer,count);*size+=count;} if(ferror(file)){fclose(file);return-1;} fclose(file); sha256_final(&hash,bytes); digest_hex(bytes,digest); snprintf(name,COUNCIL_FILE_NAME,"%s",base); return 0; }
int file_transfer_send_stream(network_socket socket,const char *path) { FILE *file=fopen(path,"rb"); uint8_t buffer[16384]; size_t count; if(!file)return-1; while((count=fread(buffer,1,sizeof(buffer),file))>0)if(network_send_bytes(socket,buffer,count)){fclose(file);return-1;} if(ferror(file)){fclose(file);return-1;} fclose(file); return 0; }
int file_transfer_receive_stream(network_socket socket,const char *directory,const char *name,uint64_t size,const char *digest,char *stored,size_t stored_size) { FILE *file; uint8_t buffer[16384],bytes[32]; char actual[65],nonce[33],temporary[1024],final[1024]; uint64_t remaining=size; size_t final_length; sha256_ctx hash; if(!file_transfer_name_is_safe(name)||authentication_nonce(nonce))return-1; if(snprintf(final,sizeof(final),"%s/%s-%s",directory,nonce,name)<0)return-1; final_length=strlen(final); if(final_length+5>=sizeof(temporary)||final_length>=stored_size)return-1; memcpy(temporary,final,final_length); memcpy(temporary+final_length,".part",6); file=fopen(temporary,"wb"); if(!file)return-1; sha256_init(&hash); while(remaining){size_t wanted=remaining>sizeof(buffer)?sizeof(buffer):(size_t)remaining; if(network_read_bytes(socket,buffer,wanted)||fwrite(buffer,1,wanted,file)!=wanted){fclose(file);remove(temporary);return-1;} sha256_update(&hash,buffer,wanted);remaining-=wanted;} if(fclose(file)){remove(temporary);return-1;} sha256_final(&hash,bytes);digest_hex(bytes,actual);if(strcmp(actual,digest)){remove(temporary);return-2;}if(rename(temporary,final)){remove(temporary);return-1;}memcpy(stored,final,final_length+1);return 0; }
int file_transfer_forward(const contact *destination,const char *local_name,const char *sender,const char *path,const char *name,uint64_t size,const char *digest,char *reply,size_t reply_size) { network_socket socket; char command[512]; if(protocol_connect_identity(destination,local_name,&socket))return-1; snprintf(command,sizeof(command),"STORE %s %s %llu %s\n",sender,name,(unsigned long long)size,digest); if(network_send(socket,command)||network_read_line(socket,reply,reply_size)<0||strcmp(reply,"READY")){network_close(socket);return-1;} if(file_transfer_send_stream(socket,path)||network_read_line(socket,reply,reply_size)<0){network_close(socket);return-1;} network_close(socket);return strcmp(reply,"STORED")?-1:0; }
